enumCorrections:
  classes: []

nonClassMemberCorrections:
  typeAliasRenames: {}
  propertyRenames: {}

standardCorrections:
  commonPrefixReplacements: {}
  ignoreFunctions: []
  ignoreProperties: []
  functions: []
  properties: []
  members: []
  classes: []

unnamedClasses:
  classes: []
